export const CATEGORIES = [
   "Transfers",
   "Supermarkets and groceries",
   "Services",
   "Utilities and Internet",
   "Pharmacies",
   "Clothes and shoes",
   "Cinema",
   "Books and stationery",
   "Digital goods",
   "Taxi",
   "Restaurants, cafes, bars",
   "Home and repair",
   "Mobile top-up",
   "Transfer from my card",
   "Transfer to my card",
   "Transfer crediting",
   "Beauty",
   "Payments by details",
   "Entertainment",
   "Sport",
   "Animals",
   "Household appliances",
   "Cash withdrawal",
   "Medical services",
   "Other",
   "Transport",
   "Train tickets",
   "Tourism",
   "Budget payments",
   "Flowers",
] as const

export const CATEGORIES_EMOJIS = {
   Transfers: "💸",
   "Supermarkets and groceries": "🛒",
   Services: "🛠️",
   "Utilities and Internet": "💡",
   Pharmacies: "💊",
   "Clothes and shoes": "👕",
   Cinema: "🍿",
   "Books and stationery": "📚",
   "Digital goods": "📱",
   Taxi: "🚕",
   "Restaurants, cafes, bars": "🍽️",
   "Home and repair": "🏠",
   "Mobile top-up": "📲",
   "Transfer from my card": "📤",
   "Transfer to my card": "📥",
   "Transfer crediting": "💰",
   Beauty: "💄",
   "Payments by details": "🏦",
   Entertainment: "🎟️",
   Sport: "🏃",
   Animals: "🐾",
   "Household appliances": "🔌",
   "Cash withdrawal": "🏧",
   "Medical services": "🩺",
   Other: "📂",
   Transport: "🚇",
   "Train tickets": "🚆",
   Tourism: "✈️",
   "Budget payments": "🏛️",
   Flowers: "💐",
} satisfies Record<(typeof CATEGORIES)[number], string>
